# Generated by Django 3.0.8 on 2020-07-11 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
