# Generated by Django 3.0.8 on 2020-07-11 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0002_delete_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('quality', models.CharField(max_length=5)),
                ('performance', models.CharField(max_length=5)),
                ('availability', models.CharField(max_length=5)),
                ('oee', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_ocurrence', models.CharField(choices=[('S', 'STOP'), ('R', 'RESUME')], max_length=200)),
                ('note', models.CharField(max_length=200)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.Machine')),
            ],
        ),
    ]
